### PR TITLE
Added ruby install scripts for pi, edison and to compile from source

### PR DESCRIPTION
**Pull request by makeupsomething**

### CODE REVIEW

**Comment by makeupsomething** [comment]
Can you check these scripts please

**Comment by yutashi** [comment]
`edison/ruby_install.sh` installs ruby 1.9.3.

```
# ruby -v
ruby 1.9.3p547 (2014-05-14 revision 45962) [i386-linux]
```

so need to fix the follow comment

```
#!/bin/bash
# Install ruby 2.4.0
```

**Comment by yutashi** [comment]
I have confirmed Ruby installation on Raspberry.

```
 $ ruby -v
ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]
```

**Comment by makeupsomething** [comment]
@yutashi Thank you

**Pull request merged**
